# Generated by Django 4.2 on 2024-11-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(blank=True, max_length=20, null=True)),
                ('lname', models.CharField(max_length=20)),
                ('regno', models.CharField(max_length=13, unique=True)),
                ('department', models.CharField(choices=[('ETE', 'Electronics and Telecommunication Engineering'), ('CSE', 'Computer Sciences and Engineering')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Score out of 100.')),
                ('comments', models.TextField(blank=True, null=True)),
                ('recruited', models.BooleanField(default=False, help_text='Recruited (Yes/No).')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='recuitz.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubs', models.JSONField(blank=True, help_text='Choose the list of clubs you are in.', null=True)),
                ('motivation', models.TextField(help_text='What motivates you?')),
                ('picture_choice', models.CharField(default='nature', help_text='Choose a picture.', max_length=50)),
                ('github_link', models.URLField(blank=True, help_text='Provide your GitHub profile link (optional).', null=True)),
                ('skills', models.JSONField(default='No Skills', help_text="Provide a list of your skills (e.g., ['Python', 'Django', 'React']).")),
                ('big_project', models.TextField(blank=True, help_text='Explain one big project or solution you have done.', null=True)),
                ('reason_to_join', models.TextField(default='I am just interested', help_text='Explain why you want to join.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='recuitz.user')),
            ],
        ),
    ]
