# Generated by Django 4.2 on 2024-11-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuitz', '0002_alter_question_clubs_alter_question_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('decription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='question',
            name='picture_choice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='regno',
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(default='CEIT', help_text='Enter your course (e.g., CEIT, TE, etc.).', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1, help_text='Choose your year of study.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='clubs',
            field=models.JSONField(blank=True, help_text="List the clubs you are in, or enter 'None' if not in any club. For other descriptions, choose 'Other' and write about yourself.", null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='skills',
            field=models.JSONField(help_text="Provide a list of your skills (e.g., ['Python', 'Django'])."),
        ),
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Choose a project to join.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recuitz.project'),
        ),
    ]
