# Generated by Django 4.2 on 2024-12-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuitz', '0003_project_remove_question_github_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mname',
        ),
        migrations.AddField(
            model_name='question',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='johndoe@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=40),
        ),
    ]
